### ISSUE TITLE
función que grafica nubes

### ISSUE THREAD

**Issue by jorobledo** [paula-rj/StratoPy#10]
Copiando el código que había puesto Paula, utilicé imshow para ver los datos de tipo CloudLayerType en cada imágen del Cloudsat. 

El problema es que al ser un graficador de imágenes, gráfica los ejes x e y en nro. de pixeles (no en latitud y tipo de nube, que es lo que queremos) con lo cual se me ocurre que, o hay que mapear pixeles a latitud/longitud y ver de cambiar los ticks en la imagen (solución media casera que empecé a implementar), o bien utilizar otra función, tipo contourf donde hacemos el mesh X, Y para longitud y tipo de nube y luego ponemos el valor de Z como el array de datos. 

Capaz no estoy al tanto de algo que sea mucho más sencillo. Si se les ocurre otra manera o algo conveniente para esto, avisen!

**Comment by paula-rj** [comment]
Buenas! No estoy entendiendo muy bien que quisieras graficar. Seria poner en el eje y Latitud, en el eje x longitud y mapear los tipos de nube en cada capa? O en el eje y poner altura, en el x latitud o longitud y hacer el grafico de tipos de nube por capa, como el de la pagina de cloudsat?
Por otra parte, esto que dijiste " _utilizar otra función, tipo contourf donde hacemos el mesh X, Y para longitud y tipo de nube y luego ponemos el valor de Z como el array de datos._" si! habria que intentarlo al menos, no se si es muy complicado o no. No es lo mas importante pero estaría bueno hacerlo.

**Comment by jorobledo** [comment]
ja, no. Ninguna de las dos cosas que describís estaba intentando. Lo que estaba intentando era graficar en el eje y la clase (0,1,2,...,9) y en el eje x la longitud o bien la latitud. Pero creo que entendí mal lo que se quería.  Cuando vi tu Colab, noté que el array que sale de 

file = SD(self.path, SDC.READ)
cld_layertype = file.select('CloudLayerType')[:]

tiene de dimensión (36950, 10). Esto guarda para cada punto (latitud, longitud) es valor del tipo de nube. Bueno, la imagen que se grafica es este array, con los 10  pixeles en el eje y, coloreado según la clasificación del tipo de nube. No se si se necesita esto entonces.

Por ahí lo podemos hablar mejor en la reunión. 

Una pregunta:

http://www.cloudsat.cira.colostate.edu/sites/default/files/data_products/images/2009231162830_17611_CS_2B-CLDCLASS_cloud_scenario_18.png

En la imagen que pongo arriba, qué es lo que se grafica en el eje y?

**Comment by paula-rj** [comment]
Ahh bien ya entendi. Creo que para esta variable 'CloudLayerType' particular no seria lo mejor. Quizas hacer eso con la variable 'CloudScenario' tenga sentido, no lo se porque no explore mucho esa alternativa. No es lo mas urgente ahora pero después podemos analizarlo.
Lo que se grafica en esa imagen en el eje y es la altura, que seria la variable 'Height' en los archivos. En el eje x esta la latitud o longitud.

**Comment by jorobledo** [comment]
cerramos esto porque nos focalizamos en los dataframe y no en graficar.
