### ISSUE TITLE
Error al  instalar Cartopy desde requirements

### ISSUE THREAD

**Issue by paula-rj** [paula-rj/StratoPy#23]
Hola! Estoy teniendo problemas para instalar Cartopy desde el requirements. Estoy con ubuntu 20.04 desde windows (WSL2). Alguien pudo solucionar esto? o solo quedaría instalarlo desde Github?
Este es el error que tira:
_ERROR: Could not find a version that satisfies the requirement Cartopy==0.19.0.post1 (from versions: 0.11.0, 0.12.0.4, 0.12.0.5, 0.13.0, 0.13.1, 0.14.0, 0.14.2, 0.15.1, 0.16.0, 0.17.0, 0.18.0b1, 0.18.0b2, 0.18.0rc1, 0.18.0, 0.19.0rc1, 0.19.0.post1, 0.20.0)                                               -bash: syntax error near unexpected token `('_            
Como si no encontrara la versión especificada pero mas abajo dice que la versión esa si existe.

**Comment by jorobledo** [comment]
Hola pau, yo lo pude instalar desde pip en WSL2. Me sorprende el syntax error que te está tirando, tal vez viene por ese lado? Acá te dice las dependencias que necesita:
https://scitools.org.uk/cartopy/docs/latest/installing.html

Proba tmb con estas:
https://techoverflow.net/2021/07/11/how-to-install-cartopy-on-ubuntu/

Estoy con ubuntu:

NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
