### ISSUE TITLE
Configuración incompatible entre tox y gh-actions

### ISSUE THREAD

**Issue by mchalela** [paula-rj/StratoPy#34]
En la seccion [gh-actions] de tox se declaran dos versiones python para correr los tests, pero en `ci.yml` solo se pide python 3.9. Esto hace que los entornos declarados en 3.8 nunca se ejecuten.

https://github.com/paula-rj/StratoPy/blob/fe7a154b5d71b7870c2ca545f0e7121aa4a4ea06/tox.ini#L4-L7

https://github.com/paula-rj/StratoPy/blob/fe7a154b5d71b7870c2ca545f0e7121aa4a4ea06/.github/workflows/ci.yml#L13

**Comment by jorobledo** [comment]
Gracias Martín! Ahí lo modifiqué, estaba mal testeando en 3.8. Me podés decir si ahí está solucionado?

**Comment by mchalela** [comment]
Ahora si! Cierro el issue
